/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MobileListing {
  'id' : bigint,
  'status' : string,
  'storage' : string,
  'submittedAt' : bigint,
  'description' : string,
  'sellerName' : string,
  'address' : string,
  'modelName' : string,
  'mobilePhoto' : [] | [ExternalBlob],
  'brand' : string,
  'phoneNumber' : string,
  'motherboardPhoto' : [] | [ExternalBlob],
  'pickupDateTime' : [] | [string],
  'condition' : string,
}
export interface StorageRate { 'storage' : string, 'rate' : bigint }
export interface SubmitListingInput {
  'mobilePhotoBlobId' : [] | [string],
  'storage' : string,
  'description' : string,
  'sellerName' : string,
  'address' : string,
  'modelName' : string,
  'motherboardPhotoBlobId' : [] | [string],
  'brand' : string,
  'phoneNumber' : string,
  'condition' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllListings' : ActorMethod<[], Array<MobileListing>>,
  'getListingById' : ActorMethod<[bigint], [] | [MobileListing]>,
  'getNewListingsCount' : ActorMethod<[], bigint>,
  'getStorageRates' : ActorMethod<[], Array<StorageRate>>,
  'submitListing' : ActorMethod<[SubmitListingInput], bigint>,
  'updateListingStatus' : ActorMethod<[bigint, string], boolean>,
  'updatePickupDateTime' : ActorMethod<[bigint, string], boolean>,
  'updateStorageRate' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];