/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MobileListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'storage' : IDL.Text,
  'submittedAt' : IDL.Int,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'address' : IDL.Text,
  'modelName' : IDL.Text,
  'mobilePhoto' : IDL.Opt(ExternalBlob),
  'brand' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'motherboardPhoto' : IDL.Opt(ExternalBlob),
  'condition' : IDL.Text,
});
export const SubmitListingInput = IDL.Record({
  'mobilePhotoBlobId' : IDL.Opt(IDL.Text),
  'storage' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'address' : IDL.Text,
  'modelName' : IDL.Text,
  'motherboardPhotoBlobId' : IDL.Opt(IDL.Text),
  'brand' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllListings' : IDL.Func([], [IDL.Vec(MobileListing)], ['query']),
  'getNewListingsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitListing' : IDL.Func([SubmitListingInput], [IDL.Nat], []),
  'updateListingStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MobileListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'storage' : IDL.Text,
    'submittedAt' : IDL.Int,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'address' : IDL.Text,
    'modelName' : IDL.Text,
    'mobilePhoto' : IDL.Opt(ExternalBlob),
    'brand' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'motherboardPhoto' : IDL.Opt(ExternalBlob),
    'condition' : IDL.Text,
  });
  const SubmitListingInput = IDL.Record({
    'mobilePhotoBlobId' : IDL.Opt(IDL.Text),
    'storage' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'address' : IDL.Text,
    'modelName' : IDL.Text,
    'motherboardPhotoBlobId' : IDL.Opt(IDL.Text),
    'brand' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllListings' : IDL.Func([], [IDL.Vec(MobileListing)], ['query']),
    'getNewListingsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitListing' : IDL.Func([SubmitListingInput], [IDL.Nat], []),
    'updateListingStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };